### PR TITLE
Apache Monitor revamp to 2.0.0

### PR DESCRIPTION
**Pull request by akshayAppd**
ApacheMonitor revamp to 2.0.0 framework

### CODE REVIEW

**Comment by venkatakonala** [comment]
1. The folder name is ApacheMonitor while the entry class is ApacheStatusMonitor. Also the jar file is apache-monitoring-extension.jar. 
    Can all these be consistent?
2. Naming for some classes are not consistent with other extensions 
   ApacheMonitoringTask -> ApacheMonitorTask
3.  In config.yml,
     metricPrefix: Custom Metrics|WebServer|
     Should'nt this be 
     metricPrefix: "Custom Metrics|ApacheMonitor(or)ApacheStatusMonitor"?
     Also by default the metricPrefix with comonent id has to be exposed.
4. In config.yml, there is no comment for numberOfThreads configuration.
5. Extensions commons version is 2.0.4. Can you change it to 2.1.0? This would need a bit of refactoring in ApacheMonitor class.
6. TODOs in the code will be checked in.

**Comment by bhuvnesh17** [comment]
Please add a one liner on what the configuration is. 
Under "Load balancing metrics" : In addition to the above specified metrics, this extension can also show metrics from mod_jk status.

There are no other metrics before this section. Can you maybe rewrite this part?
Also, please add a description about the following and where the files can be found : httpd.conf & worker.properties file

**Comment by venkatakonala** [comment]
1. CHANGES.md needs to be changed to CHANGELOG.md and updated.
2. LICENSE.txt needs to be updated to the latest one(copyright 2018).
3. Code TODOs will be checked in along with some changes I made directly without TODOs.
4. Please make unit test changes based on these changes.

**Comment by venkatakonala** [comment]
1. CHANGELOG.md needs to be in reverse chronological order. I already made that change. Please check.
2. Is CONTRIBUTING.md required? If not, please remove it.
3. Added the required comment for numberOfThreads, please chack and let me know if you have any doubt.
4. Also there is no test for CustomStats, can you please add that?

**Comment by venkatakonala** [comment]
1. I do not see steps for adding mutual auth in the README.md. Can you please update that?
2. Also the I think you can keep the fields required for the mutual auth in the default config.yml.
3. Please add a unit test for this case to test. Refer to HttpClientBuilderTest class in appd-exts-commons for sample tests.

**Comment by venkatakonala** [comment]
Just wanted to confirm if all the manual testing cases in the development and testing guidelines have been tested. If affirmative, then the code can be merged.

**Review by venkatakonala — COMMENTED** [review]
Please close this issue before merging
https://github.com/Appdynamics/apache-monitoring-extension/issues/2

**Review by venkatakonala — CHANGES_REQUESTED** [review]
I just saw the recent changes made and found the following:
1. The "HeartBeat" metric is not in the right place at all. Infact there is a chance that the HeartBeat metric is not created at all if the customer removes "ServerStats". Also the way in which the value for HeartBeat metric is being calculated is wrong. Please correct this.
2. Also, Please close this issue #2.

**Pull request merged**
